GMX_PREFIX = 'gmx'

NAME_INPUT_TEMPLATE_SLAB = 'INPUT_TEMPLATE_SLAB'
NAME_TEMP_RAMP_START = 'TEMP_RAMP_START'
NAME_TEMP_RAMP_STOP = 'TEMP_RAMP_STOP'


NAME_EQ_NVT = 'EQ_NVT'
NAME_EQ_SURFTEN = 'EQ_SURFTEN'; NAME_PRO_SURFTEN = 'PRO_SURFTEN'

NAME_ELONGATED = 'ELONGATED_BOX_PLACEHOLDER'

GENERAL_LOCAL_DATA = 'raw_general_data_for'
GENERAL_GLOBAL_DATA = 'aggregate_general_Data'

DENS_LOCAL_DATA = 'raw_dens_Data'
DENS_GLOBAL_DATA = 'aggregate_dens_Data_fromMIN-MAX'

NAME_EQ_CHUNK_COUNT = int(1)
NAME_PRO_CHUNK_COUNT = int(1)

# chunked

EQ_SURFTEN_CHUNK_TO_STARTING_GRO_FILE = {
    0 : f'{NAME_ELONGATED}',
    1 : f'{NAME_EQ_SURFTEN}_CHUNK_1'
}

PRO_SURFTEN_CHUNK_TO_STARTING_GRO_FILE = {
    0 : f'{NAME_EQ_SURFTEN}_CHUNK_1',
    1 : f'{NAME_PRO_SURFTEN}_CHUNK_1'
}
